version: "3"
services:
  url-shortener:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      FLASK_APP: ./app.py
      FLASK_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    command: flask run