version: "3"
services:
  url-shortener:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
  # db: 
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: develop